### ISSUE TITLE
Some issue rant and rage (beerbrewing fork)

### ISSUE THREAD

**Issue by beerbrewing** [kevleyski/git_diff#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Blah

**Comment by beerbrewing** [comment]
And make it snappy

**Comment by beerbrewing** [comment]
Still waiting on this ;-)

**Comment by kevleyski** [comment]
Sheesh calm your farm

**Comment by beerbrewing** [comment]
(ok)

**Comment by kevleyski** [comment]
Alright its fixed

**Comment by kevleyski** [comment]
Email test
